language: common-lisp
os: linux

notifications:
  email: false

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-8-jre

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

# This gets the environment overridden to set the lisp implementation to test
test-job: &test
  stage: test
  install:
    # Install Roswell
    - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
    - ros install fukamachi/rove
    - pip install Flask
  before_script:
    - echo "JSON-Schema-Test-Suite"
    - git submodule status JSON-Schema-Test-Suite/
    - ros --version
    - ros config
    - ros -s json-schema -e '(print "precompiled json-schema")'
    - ./JSON-Schema-Test-Suite/bin/jsonschema_suite serve &
  script:
    - ros exec rove json-schema.asd

jobs:
  fast_finish: true
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
  include:
    # - <<: *test
    #   env:
    #     - LISP=sbcl-bin COVERALLS=true
    - <<: *test
      env:
        - LISP=ccl-bin
    # - <<: *test
    #   env:
    #     - LISP=ecl
    # - <<: *test
    #   env:
    #     - LISP=allegro
    # - <<: *test
    #   env:
    #     - LISP=abcl
    - name: update docs
      stage: deploy
      before_script:
        - docker pull quay.io/fisxoj/coo:master
      script:
        - docker run --rm -it -v $PWD:/work:Z quay.io/fisxoj/coo:master
      deploy:
        provider: pages:git
        edge: true
        local_dir: docs
      if: type = push AND branch = master
